services:
  arangodb:
    image: arangodb/core-preview:4.0-nightly
    environment:
      ARANGO_ROOT_PASSWORD: passwd
    ports:
      - "8529:8529"
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - --quiet
        - --tries=1
        - --header
        - "Authorization: Basic cm9vdDpwYXNzd2Q="
        - http://127.0.0.1:8529/_api/version
      interval: 5s
      timeout: 5s
      retries: 20
